# Site settings
title: My Proects
email: dan.kirkpatrick<at>gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my space to document some of my ongoing projects.  Read
  here for information about my projects with students in our 
  Maker's Club, my 3D additive and subtractive manufacturing robots,
  power supplies, and more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dankirkpatrick.github.io" # the base hostname & protocol for your site
twitter_username: kirkpatrick_dan
github_username:  dankirkpatrick

# Build settings
markdown: kramdown
